"""
Asset Model

Digital assets (images, videos, etc.) used throughout the project.
"""

from enum import Enum
from typing import TYPE_CHECKING, Optional
from uuid import UUID

from sqlalchemy import ForeignKey, Integer, String, Text
from sqlalchemy import Enum as SAEnum
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from scenemachine.models.base import Base, TimestampMixin, UUIDMixin, JSONType

if TYPE_CHECKING:
    from scenemachine.models.character import Character


class AssetType(str, Enum):
    """Types of assets in the system."""

    # Reference images
    CHARACTER_REFERENCE = "character_reference"  # User-uploaded character reference
    CHARACTER_GENERATED = "character_generated"  # AI-generated character image
    LOCATION_REFERENCE = "location_reference"  # Location/set reference
    STYLE_REFERENCE = "style_reference"  # Visual style reference

    # Generated content
    SHOT_VIDEO = "shot_video"  # Generated video for a shot
    SHOT_AUDIO = "shot_audio"  # Generated audio for a shot (TTS dialogue)
    SHOT_THUMBNAIL = "shot_thumbnail"  # Thumbnail for a shot
    SHOT_FRAMES = "shot_frames"  # Individual frames from a shot
    SCENE_VIDEO = "scene_video"  # Assembled scene video
    FINAL_EXPORT = "final_export"  # Final movie export

    # AI model artifacts
    CHARACTER_EMBEDDING = "character_embedding"  # Face/character embedding
    CHARACTER_LORA = "character_lora"  # Character LoRA weights

    # Temporary/working files
    TEMP_UPLOAD = "temp_upload"  # Temporary upload
    WORKING_FILE = "working_file"  # Intermediate working file


class AssetStatus(str, Enum):
    """Asset processing status."""

    UPLOADING = "uploading"  # Upload in progress
    UPLOADED = "uploaded"  # Upload complete, not processed
    PROCESSING = "processing"  # Being processed
    READY = "ready"  # Ready for use
    FAILED = "failed"  # Processing failed
    DELETED = "deleted"  # Marked for deletion


class Asset(Base, UUIDMixin, TimestampMixin):
    """
    A digital asset (image, video, model weights, etc.) used in the project.

    Assets can be uploaded by users, generated by AI, or created during
    processing. They are associated with characters, shots, or the project
    in general.

    Attributes:
        project_id: Foreign key to the project (for all assets)
        character_id: Optional foreign key to character (for character assets)
        shot_id: Optional foreign key to shot (for shot assets)
        asset_type: Type classification
        status: Processing status
        filename: Original or generated filename
        file_path: Storage path (relative to project directory)
        file_hash: SHA-256 hash for integrity
        file_size_bytes: File size
        mime_type: MIME type
        metadata: Type-specific metadata (JSON)
    """

    __tablename__ = "assets"

    # Foreign keys - all assets belong to a project
    project_id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("projects.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # Optional associations
    character_id: Mapped[Optional[UUID]] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("characters.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    shot_id: Mapped[Optional[UUID]] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("shots.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    scene_id: Mapped[Optional[UUID]] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("scenes.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    # Asset classification
    asset_type: Mapped[AssetType] = mapped_column(
        SAEnum(AssetType, name="asset_type"),
        nullable=False,
        index=True,
    )
    status: Mapped[AssetStatus] = mapped_column(
        SAEnum(AssetStatus, name="asset_status"),
        default=AssetStatus.UPLOADED,
        nullable=False,
    )

    # File information
    filename: Mapped[str] = mapped_column(String(255), nullable=False)
    file_path: Mapped[str] = mapped_column(String(512), nullable=False)
    file_hash: Mapped[Optional[str]] = mapped_column(String(64), nullable=True)  # SHA-256
    file_size_bytes: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    mime_type: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)

    # Display information
    display_name: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Type-specific metadata (named asset_metadata to avoid SQLAlchemy reserved attribute)
    asset_metadata: Mapped[Optional[dict]] = mapped_column(JSONType, nullable=True)
    # Structure varies by asset_type:
    #
    # For images (CHARACTER_REFERENCE, CHARACTER_GENERATED, etc.):
    # {
    #     "width": 1024,
    #     "height": 1024,
    #     "format": "png",
    #     "color_space": "sRGB",
    #     "has_alpha": false,
    #     "face_detected": true,
    #     "face_bbox": [100, 100, 400, 400],
    #     "quality_score": 0.95
    # }
    #
    # For videos (SHOT_VIDEO, SCENE_VIDEO):
    # {
    #     "width": 1920,
    #     "height": 1080,
    #     "duration_seconds": 3.5,
    #     "frame_rate": 24,
    #     "total_frames": 84,
    #     "codec": "h264",
    #     "bitrate_kbps": 5000,
    #     "has_audio": false
    # }
    #
    # For embeddings (CHARACTER_EMBEDDING):
    # {
    #     "model": "insightface",
    #     "dimensions": 512,
    #     "source_image_id": "uuid",
    #     "created_at": "2024-01-15T10:30:00Z"
    # }
    #
    # For LoRA (CHARACTER_LORA):
    # {
    #     "base_model": "SDXL",
    #     "rank": 32,
    #     "alpha": 16,
    #     "training_steps": 1000,
    #     "training_images": 10,
    #     "trigger_word": "ohwx person"
    # }

    # Source tracking (for generated assets)
    source_info: Mapped[Optional[dict]] = mapped_column(JSONType, nullable=True)
    # Structure:
    # {
    #     "generated": true,
    #     "model": "stable-diffusion-xl",
    #     "generation_job_id": "uuid",
    #     "seed": 12345,
    #     "prompt": "...",
    #     "source_asset_ids": ["uuid1", "uuid2"]
    # }

    # Relationships
    character: Mapped[Optional["Character"]] = relationship(
        "Character",
        back_populates="reference_assets",
        foreign_keys=[character_id],
    )

    @property
    def is_image(self) -> bool:
        """Check if asset is an image."""
        image_types = {
            AssetType.CHARACTER_REFERENCE,
            AssetType.CHARACTER_GENERATED,
            AssetType.LOCATION_REFERENCE,
            AssetType.STYLE_REFERENCE,
            AssetType.SHOT_THUMBNAIL,
        }
        return self.asset_type in image_types

    @property
    def is_video(self) -> bool:
        """Check if asset is a video."""
        video_types = {
            AssetType.SHOT_VIDEO,
            AssetType.SCENE_VIDEO,
            AssetType.FINAL_EXPORT,
        }
        return self.asset_type in video_types

    @property
    def is_model_artifact(self) -> bool:
        """Check if asset is an AI model artifact."""
        model_types = {
            AssetType.CHARACTER_EMBEDDING,
            AssetType.CHARACTER_LORA,
        }
        return self.asset_type in model_types

    @property
    def is_ready(self) -> bool:
        """Check if asset is ready for use."""
        return self.status == AssetStatus.READY

    @property
    def file_size_display(self) -> str:
        """Human-readable file size."""
        if not self.file_size_bytes:
            return "Unknown"

        size = self.file_size_bytes
        for unit in ["B", "KB", "MB", "GB"]:
            if size < 1024:
                return f"{size:.1f} {unit}"
            size /= 1024
        return f"{size:.1f} TB"

    @property
    def dimensions(self) -> Optional[tuple[int, int]]:
        """Get image/video dimensions if available."""
        if self.asset_metadata:
            width = self.asset_metadata.get("width")
            height = self.asset_metadata.get("height")
            if width and height:
                return (width, height)
        return None

    @property
    def duration_seconds(self) -> Optional[float]:
        """Get video duration if available."""
        if self.is_video and self.asset_metadata:
            return self.asset_metadata.get("duration_seconds")
        return None

    def __repr__(self) -> str:
        """String representation."""
        return (
            f"<Asset(id={self.id}, "
            f"type={self.asset_type.value}, "
            f"filename='{self.filename}', "
            f"status={self.status.value})>"
        )
