"""Screenplay model - represents uploaded and parsed screenplay documents."""

from enum import Enum
from typing import TYPE_CHECKING, List, Optional
from uuid import UUID

from sqlalchemy import Boolean, ForeignKey, String, Text
from sqlalchemy import Enum as SAEnum
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from .base import Base, TimestampMixin, UUIDMixin

if TYPE_CHECKING:
    from .project import Project


class ScreenplayFormat(str, Enum):
    """Supported screenplay file formats."""

    FOUNTAIN = "fountain"  # .fountain files (primary format)
    PDF = "pdf"  # PDF screenplays (OCR may be required)
    FDX = "fdx"  # Final Draft XML format
    PLAIN_TEXT = "plain_text"  # Plain text (best effort parsing)


class Screenplay(Base, UUIDMixin, TimestampMixin):
    """A screenplay document associated with a project.

    Contains both the original file and parsed structured data.
    The screenplay is the source of truth for the movie's content.
    """

    __tablename__ = "screenplays"

    # Foreign key to project
    project_id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("projects.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,
    )

    # Original file information
    original_filename: Mapped[str] = mapped_column(String(255), nullable=False)
    original_format: Mapped[ScreenplayFormat] = mapped_column(
        SAEnum(ScreenplayFormat, name="screenplay_format"),
        nullable=False,
    )
    file_hash: Mapped[str] = mapped_column(String(64), nullable=False)  # SHA-256

    # Storage path (relative to project directory)
    original_file_path: Mapped[str] = mapped_column(String(512), nullable=False)

    # Parsed content (stored as JSON for flexibility)
    parsed_content: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True)
    # Structure:
    # {
    #     "title_page": {
    #         "title": "...",
    #         "author": "...",
    #         "contact": "...",
    #         "draft_date": "..."
    #     },
    #     "elements": [
    #         {"type": "scene_heading", "text": "INT. OFFICE - DAY", ...},
    #         {"type": "action", "text": "...", ...},
    #         {"type": "character", "name": "JOHN", ...},
    #         {"type": "dialogue", "text": "...", ...},
    #         ...
    #     ],
    #     "metadata": {
    #         "page_count": 120,
    #         "scene_count": 45,
    #         "character_count": 12,
    #         "estimated_runtime_minutes": 120
    #     }
    # }

    # Movie plan (generated by AI, approved by user)
    movie_plan: Mapped[Optional[dict]] = mapped_column(JSONB, nullable=True)
    # Structure:
    # {
    #     "overview": {
    #         "genre": "thriller",
    #         "tone": "dark, suspenseful",
    #         "themes": ["betrayal", "redemption"],
    #         "visual_style": "neo-noir"
    #     },
    #     "characters": [...],
    #     "acts": [...],
    #     "key_scenes": [...],
    #     "visual_motifs": [...],
    #     "color_palette": {...},
    #     "pacing_notes": "..."
    # }

    movie_plan_approved: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)

    # Parsing metadata
    is_parsed: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    parse_errors: Mapped[Optional[List[str]]] = mapped_column(JSONB, nullable=True)
    parse_warnings: Mapped[Optional[List[str]]] = mapped_column(JSONB, nullable=True)

    # Relationships
    project: Mapped["Project"] = relationship("Project", back_populates="screenplay")

    @property
    def title(self) -> Optional[str]:
        """Extract title from parsed content."""
        if self.parsed_content:
            title_page = self.parsed_content.get("title_page", {})
            return title_page.get("title")
        return None

    @property
    def author(self) -> Optional[str]:
        """Extract author from parsed content."""
        if self.parsed_content:
            title_page = self.parsed_content.get("title_page", {})
            return title_page.get("author")
        return None

    @property
    def character_names(self) -> List[str]:
        """Extract unique character names from parsed content."""
        if not self.parsed_content:
            return []
        characters = set()
        for element in self.parsed_content.get("elements", []):
            if element.get("type") == "character":
                name = element.get("name", "").strip().upper()
                if name:
                    characters.add(name)
        return sorted(characters)

    @property
    def scene_headings(self) -> List[str]:
        """Extract scene headings from parsed content."""
        if not self.parsed_content:
            return []
        headings = []
        for element in self.parsed_content.get("elements", []):
            if element.get("type") == "scene_heading":
                headings.append(element.get("text", ""))
        return headings

    @property
    def page_count(self) -> Optional[int]:
        """Get page count from metadata."""
        if self.parsed_content:
            metadata = self.parsed_content.get("metadata", {})
            return metadata.get("page_count")
        return None

    def __repr__(self) -> str:
        """String representation."""
        return f"<Screenplay(id={self.id}, title='{self.title}', format={self.original_format.value})>"
