"""
Screenplay Model

A screenplay document associated with a project.
"""

from enum import StrEnum
from typing import TYPE_CHECKING
from uuid import UUID

from sqlalchemy import Boolean, ForeignKey, String
from sqlalchemy import Enum as SAEnum
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from scenemachine.models.base import Base, JSONType, TimestampMixin, UUIDMixin

if TYPE_CHECKING:
    from scenemachine.models.project import Project


class ScreenplayFormat(StrEnum):
    """Supported screenplay file formats."""

    FOUNTAIN = "fountain"  # .fountain files (native support)
    PDF = "pdf"  # PDF screenplays (OCR may be required)
    FDX = "fdx"  # Final Draft XML format
    PLAIN_TEXT = "plain_text"  # Plain text (best effort parsing)


class Screenplay(Base, UUIDMixin, TimestampMixin):
    """
    A screenplay document associated with a project.

    Contains both the original file reference and parsed structured data.
    The screenplay is the foundation from which the Movie Plan, characters,
    and scenes are derived.

    Attributes:
        project_id: Foreign key to the parent project
        original_filename: Name of the uploaded file
        original_format: Detected file format
        file_hash: SHA-256 hash for integrity verification
        original_file_path: Path to stored file (relative to project directory)
        parsed_content: Structured content after parsing (JSON)
        movie_plan: AI-generated movie plan (JSON)
        movie_plan_approved: Whether user has approved the plan
        is_parsed: Whether parsing is complete
        parse_errors: Any errors encountered during parsing
    """

    __tablename__ = "screenplays"

    # Foreign key to project
    project_id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("projects.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,  # One screenplay per project
    )

    # Original file information
    original_filename: Mapped[str] = mapped_column(String(255), nullable=False)
    original_format: Mapped[ScreenplayFormat] = mapped_column(
        SAEnum(ScreenplayFormat, name="screenplay_format"),
        nullable=False,
    )
    file_hash: Mapped[str] = mapped_column(String(64), nullable=False)  # SHA-256

    # Storage paths (relative to project directory)
    original_file_path: Mapped[str] = mapped_column(String(512), nullable=False)

    # Parsed content (stored as JSON for flexibility)
    parsed_content: Mapped[dict | None] = mapped_column(JSONType, nullable=True)
    # Parsed content structure:
    # {
    #     "title_page": {
    #         "title": "My Movie",
    #         "author": "Writer Name",
    #         "contact": "email@example.com",
    #         "draft_date": "2024-01-15",
    #         "copyright": "2024"
    #     },
    #     "elements": [
    #         {
    #             "type": "scene_heading",
    #             "scene_number": "1",
    #             "location": "COFFEE SHOP",
    #             "time_of_day": "DAY",
    #             "int_ext": "INT",
    #             "line_number": 10
    #         },
    #         {
    #             "type": "action",
    #             "text": "SARAH enters the busy coffee shop...",
    #             "line_number": 12
    #         },
    #         {
    #             "type": "character",
    #             "name": "SARAH",
    #             "line_number": 14
    #         },
    #         {
    #             "type": "dialogue",
    #             "text": "I'll have a latte, please.",
    #             "line_number": 15
    #         },
    #         {
    #             "type": "parenthetical",
    #             "text": "(nervously)",
    #             "line_number": 16
    #         },
    #         {
    #             "type": "transition",
    #             "text": "CUT TO:",
    #             "line_number": 20
    #         }
    #     ],
    #     "metadata": {
    #         "page_count": 120,
    #         "scene_count": 45,
    #         "character_count": 12,
    #         "word_count": 25000,
    #         "estimated_runtime_minutes": 120
    #     }
    # }

    # Movie plan (generated by AI, approved by user)
    movie_plan: Mapped[dict | None] = mapped_column(JSONType, nullable=True)
    movie_plan_approved: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    # Movie plan structure:
    # {
    #     "title": "My Movie",
    #     "logline": "A one-sentence summary...",
    #     "synopsis": "A longer summary...",
    #     "genre": ["drama", "thriller"],
    #     "tone": "dark and suspenseful",
    #     "themes": ["redemption", "family"],
    #     "visual_style": {
    #         "cinematography": "naturalistic",
    #         "color_palette": "muted, desaturated",
    #         "lighting": "high contrast",
    #         "era_aesthetic": "contemporary",
    #         "references": ["No Country for Old Men", "Sicario"]
    #     },
    #     "character_summaries": [
    #         {
    #             "name": "SARAH",
    #             "role": "protagonist",
    #             "description": "A determined journalist...",
    #             "arc": "From naive idealist to hardened realist"
    #         }
    #     ],
    #     "act_structure": {
    #         "act_1": {"scenes": ["1", "2", "3"], "summary": "..."},
    #         "act_2a": {"scenes": ["4", "5", "6"], "summary": "..."},
    #         "act_2b": {"scenes": ["7", "8", "9"], "summary": "..."},
    #         "act_3": {"scenes": ["10", "11", "12"], "summary": "..."}
    #     },
    #     "estimated_runtime_minutes": 95,
    #     "generation_metadata": {
    #         "model": "claude-3-opus",
    #         "generated_at": "2024-01-15T10:30:00Z",
    #         "version": 1
    #     }
    # }

    # Parsing metadata
    is_parsed: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    parse_errors: Mapped[list | None] = mapped_column(JSONType, nullable=True)
    # Parse errors structure:
    # [
    #     {
    #         "line_number": 45,
    #         "error_type": "invalid_scene_heading",
    #         "message": "Could not parse scene heading",
    #         "severity": "warning"
    #     }
    # ]

    # Relationships
    project: Mapped["Project"] = relationship("Project", back_populates="screenplay")

    @property
    def title(self) -> str | None:
        """Extract title from parsed content."""
        if self.parsed_content:
            title_page = self.parsed_content.get("title_page", {})
            return title_page.get("title")
        return None

    @property
    def author(self) -> str | None:
        """Extract author from parsed content."""
        if self.parsed_content:
            title_page = self.parsed_content.get("title_page", {})
            return title_page.get("author")
        return None

    @property
    def character_names(self) -> list[str]:
        """Extract unique character names from parsed content."""
        if not self.parsed_content:
            return []
        characters: set[str] = set()
        for element in self.parsed_content.get("elements", []):
            if element.get("type") == "character":
                name = element.get("name", "").strip().upper()
                if name:
                    characters.add(name)
        return sorted(characters)

    @property
    def scene_count(self) -> int:
        """Count number of scenes in parsed content."""
        if not self.parsed_content:
            return 0
        return sum(
            1
            for element in self.parsed_content.get("elements", [])
            if element.get("type") == "scene_heading"
        )

    @property
    def page_count(self) -> int | None:
        """Get page count from metadata."""
        if self.parsed_content:
            metadata = self.parsed_content.get("metadata", {})
            return metadata.get("page_count")
        return None

    def __repr__(self) -> str:
        """String representation."""
        return (
            f"<Screenplay(id={self.id}, title='{self.title}', format={self.original_format.value})>"
        )
