apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scenemachine-uploads
  namespace: scenemachine
  labels:
    app.kubernetes.io/name: scenemachine
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scenemachine-outputs
  namespace: scenemachine
  labels:
    app.kubernetes.io/name: scenemachine
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard
